### ISSUE TITLE
Build and deployment instructions for GUI

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1]
What we need is either a wiki page or a markdown page under the /gui dir with the following
a) build instructions for contributors
b) instructions for running/testing in docker on top of whatever desktop environment a contributors may work on
c) deployment instructions for anyone with actual rpi hardware

You could start by trying some of the script commends found in the Circle CI script [here](https://github.com/RespiraWorks/VentilatorSoftware/blob/master/.circleci/config.yml)

**Comment by hhff** [comment]
@rwilbur - let's link on this on slack! I'm working on improving gui build stuff at the moment

**Comment by martukas** [comment]
@neelfirst and @brmurray indicated that this is actually urgently needed, so I am re-adding this to alpha. It is not obvious how to do this to anyone who doesn't work with it daily and will be needed for hardware testers on a regular basis throughout beta and beyond.

**Comment by hhff** [comment]
kk, im on it @martukas

**Comment by hhff** [comment]
Waiting until https://github.com/RespiraWorks/VentilatorSoftware/pull/95 is merged as docs depend on this

**Comment by martukas** [comment]
Deployment scripts now handle this. Docker is no longer relevant.
