### ISSUE TITLE
Model Bespoke Venturi Configurations

### ISSUE THREAD

**Issue by tijanim** [RespiraWorks/Ventilator#1008]
Create CAD model configurations and drawings for the oxygen, inhale, and exhale venturi models.

**CAD Pointers**
The features exist already in the model, they just need iPart configurations so that model configs can be used in the assembly model.

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any

**Comment by martukas** [comment]
closed in #1008
