### ISSUE TITLE
Display panel, filter panel and enclosure readme update

### ISSUE THREAD

**Issue by KishanKoradiya** [RespiraWorks/Ventilator#1010]
**Folder/Page:**
The missing information can be seen in the following links:
[https://github.com/RespiraWorks/Ventilator/tree/master/manufacturing/enclosed_build/display_panel](https://github.com/RespiraWorks/Ventilator/tree/master/manufacturing/enclosed_build/display_panel)
[https://github.com/RespiraWorks/Ventilator/tree/master/manufacturing/enclosed_build/enclosure](https://github.com/RespiraWorks/Ventilator/tree/master/manufacturing/enclosed_build/enclosure)
[https://github.com/RespiraWorks/Ventilator/tree/master/manufacturing/enclosed_build/filter_panel](https://github.com/RespiraWorks/Ventilator/tree/master/manufacturing/enclosed_build/filter_panel)

**Timing considerations:**
Same as v0.3 deadline

**Task:**
The current readme for all the display panel, filter panel and enclosure, in the manufacturing folder, have quite a few TODOs. The task is to accurately and exhaustively document any updates to the designs and provide complete information regarding those features.

**Subtasks:**
* [ ] Correct folder/file names, according to file naming conventions in the wiki, if necessary

**Comment by martukas** [comment]
Implemented in #1021
