### ISSUE TITLE
Final drawing and exports update for v0.3

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1041]
**What has to be done**
Should create and/or update:
* DXF exports for all acrylic components, drawings and thumbnails
* STL exports for all 3d-printable components (drawings and thumbnails also preferred, on  best effort basis)
* Drawings and thumbnails for most other assemblies, on a best effort basis.
* General assembly could use a few renderings with some components selectively hidden to demonstrate the assembly process

Important considerations:
* make sure everything is in metric
* make sure all thumbnails are either 600 or 800 pixels in height, or whatever matches the renderings that they are next to in markdown tables
* most STLs should be up to date, and it may be confirmed by when the CAD vs. when the exports were last committed
* If assemblies are not complete or something makes it impractical to produce these, follow the priorities in the first list above to have these done by our milestone deadline.

**How do you know it has to be done**
Some of these are out of date or completely missing. In particular, there is nothing for the main pneumatics tray acrylic.
The others are there but might be out of date.

**Code pointers**
Crawl through all the pages in the manufacturing directory of the repo.

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any

**Comment by martukas** [comment]
The scope of this may be impacted by whether changes requested in the following tickets have been merged:
* sensor tubing #1039 
* main power input #1040 
* cooling fan #1034 
* custom elbows #1019 

As described in the main ticket body, this is on a best effort basis. The 4 components listed above are in order of priority.

**Comment by tijanim** [comment]
### Drawings To be Created
***Parts in Bold are priority for drawing creation**
_*Italicized parts require .stl/.dxf exports_

- [ ] GA
     - [ ] Internals Assembly     
          - [ ] _**Pneumatics Tray Acrylic**_
          - [ ] **Equipment Bracket**
          - [ ] **Filter Panel Assembly**
               - [ ] **_Lower Faceplate_**
          - [ ] Pinch Valve Assembly
          - [ ] Blower Assembly
          - [ ] Venturi
          - [ ] **_Oxygen Manifold_**
          - [ ] Pinch Valve Assembly
          - [ ] **Upper Faceplate Assembly**
               - [ ] **_Upper Faceplate Acrylic_**
     - [ ] **Enclosure Assembly**
          - [ ] **Enclosure**
