### ISSUE TITLE
`stm32-test` build failing at link time

### ISSUE THREAD

**Issue by dheater** [RespiraWorks/Ventilator#1046]
Please take the time to describe the bug in detail, so other contributors can pick it up and implement or declare done/obsolete in case it was fixed out of band.

**Current behavior**
When I run `pio run -e stm32-test` I get the following link errors:
```
Building in release mode
Linking .pio/build/stm32-test/firmware.elf
/home/dheater/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: .pio/build/stm32-test/libe99/libhal.a(hal_stm32.o): in function `HalApi::InitUARTs()':
hal_stm32.cpp:(.text._ZN6HalApi9InitUARTsEv+0x150): undefined reference to `dmaUART'
/home/dheater/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: .pio/build/stm32-test/libe99/libhal.a(uart_dma.o): in function `DMA1_CH2_ISR()':
uart_dma.cpp:(.text._Z12DMA1_CH2_ISRv+0x14): undefined reference to `dmaUART'
/home/dheater/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: .pio/build/stm32-test/libe99/libhal.a(uart_dma.o): in function `DMA1_CH3_ISR()':
uart_dma.cpp:(.text._Z12DMA1_CH3_ISRv+0x14): undefined reference to `dmaUART'
/home/dheater/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: .pio/build/stm32-test/libe99/libhal.a(uart_dma.o): in function `UART3_ISR()':
uart_dma.cpp:(.text._Z9UART3_ISRv+0x8): undefined reference to `dmaUART'
collect2: error: ld returned 1 exit status
*** [.pio/build/stm32-test/firmware.elf] Error 1
```

**Expected behavior**

Compiles and links without error.

- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any

**Comment by asmodai27** [comment]
stm32-test is a development environment which was used for sharing Work In Progress with other team members. It remains  unmaintained when there is no need for it, and in its current state way behind the main stm32 environment.

I'd say what this needs is a proper documentation so people are not surprised that this does not work at a given point in time.
