### ISSUE TITLE
Watchdog timer not connect on PCB

### ISSUE THREAD

**Issue by EnziinSystem** [RespiraWorks/Ventilator#1118]
I see watchdog timer STWD100NYWY3F not connect to anything IC while it must connect to Reset MCU pin.

Please view attach images
![p1](https://user-images.githubusercontent.com/25495466/120137883-7d6c4180-c1ff-11eb-8570-78a90644a48c.png)
![p2](https://user-images.githubusercontent.com/25495466/120137888-7e9d6e80-c1ff-11eb-897d-e4d5738e7535.png)

**Comment by martukas** [comment]
@EnziinSystem which files are you referring to? Two versions of the PCB currently reside in the master branch of the repo, so a bit more precision in identifying would help.

**Comment by inceptionev** [comment]
@EnziinSystem thanks so much for submitting an issue!  This is from a previous version of the PCB where we had an unconnected watchdog for experimentation.  The current version of the PCB (Rev A) uses the STM32 internal watchdog, so this circuit has been removed.
