### ISSUE TITLE
Not found RespiraWorks.lib and RespiraWorks_Std.lib

### ISSUE THREAD

**Issue by EnziinSystem** [RespiraWorks/Ventilator#1119]
When I open schematic in Kicad then I get the error message missing libraries.

RespiraWorks.lib and RespiraWorks_Std.lib

Please attach libraries to the project.

![p3](https://user-images.githubusercontent.com/25495466/120145666-199d4500-c20e-11eb-9632-5d1df65e3878.png)
![p6](https://user-images.githubusercontent.com/25495466/120145667-1ace7200-c20e-11eb-8866-f1e8a94bfce6.png)

**Comment by martukas** [comment]
Looks like our cikad libraries repo is held private for now, making it impossible for outsiders to work with the PCB design. This is a detractor from the "open-sourcedness" of our project.

**Comment by EnziinSystem** [comment]
Hello,

Is there any way to solve this problem?

I think the component library is not a private license.

I just need to open the design diagram in KiCad.

Thanks.

**Comment by inceptionev** [comment]
@EnziinSystem thanks so much for submitting an issue!  We are looking into this, and we should have it resolved soon.  We need to scrub our library to make sure we don't have resources with license conflicts with a public open-source license.  Once we have this resolved, we can make it public.

**Comment by inceptionev** [comment]
The kicad project should have symbols and footprints embedded into it so it can be opened without access to the RespiraWorks library, it may ask you to "Rescue libraries" or something like this, and if you select OK, it will open.  I will try this on a fresh installation of kicad to confirm if it works.

**Comment by inceptionev** [comment]
@EnziinSystem this library has now been made accessible.  https://github.com/RespiraWorks/KiCad-Library  Thanks for your ticket.
