### ISSUE TITLE
Stainless steel to painted steel

### ISSUE THREAD

**Issue by gokcemay** [RespiraWorks/Ventilator#1125]
Please take the time to describe the issue in detail, so that other contributors can pick it up and implement or declare it done/obsolete in case it was fixed out of band.

**Current behaviour/situation**
* Enclosure and tray are made from stainless steel now. Stainless steel is 5 times more expansive than plain carbon steel, such as AISI 1020. We can change the design to AISI 1020. That will reduce cost, improve manufacturability and we can use color in design. 

**Expected state/behaviour**
* We have to check the standarts. Is there any reason not to use electrostatic paint on steel?

**How do you know it is wrong**

Stainless steel is expensive. Plain carbon steel is cheaper and used for manufacturing. It is easy to tool for and weights less. Also you can paint steel. That will solve design esthetics issue.

Link to requirements or risk analysis if applicable.

**Starting points**
You don't need to change any CAD files. We just change material and add paint info. The painted enclosure color is RAL 9016, internal tray is RAL 7035. Other RAL colors can be found here: [https://www.ralcolorchart.com/](https://www.ralcolorchart.com/)

![IMG_20210708_181253](https://user-images.githubusercontent.com/9111126/125498440-cd87c2dd-b0b7-46f6-9d4a-5c0c5e3dedb8.jpg)

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any

**Comment by martukas** [comment]
Also may be relevant - we have a branding guide with recommended colors based on RespiraWorks logo:
https://drive.google.com/file/d/14AHDmDAq0j-ZFKyvWVxcClCTFuS74Vht/view?usp=sharing

**Comment by gokcemay** [comment]
Pricing doesn't change considirable amount for US based manufacturing.
