### ISSUE TITLE
PEM Nuts on acrylic is hard to assemble

### ISSUE THREAD

**Issue by gokcemay** [RespiraWorks/Ventilator#1126]
Please take the time to describe the issue in detail, so that other contributors can pick it up and implement or declare it done/obsolete in case it was fixed out of band.

**Current behaviour/situation**
* There are 6 PEM nuts on acrylic tray. These are fixed to internal tray. However tolerance buildup is an issue. Some bolts can't be assembeled.
* One way to fix it is to measure locations before cutting acrylic and fixing PEM nuts. 
* Another way to fix it is to increase hole sizes on internal tray. An increase to 5mm diameter might be enough.

**Expected state/behaviour**
* In order to change internal tray CAD files should be updated.

**How do you know it is wrong**

I tried to assemble it and found that there is a problem. Tighter production tolerances might solve the issue.

Link to requirements or risk analysis if applicable.

**Starting points**
Check tolerance buildup. What is the maximum issue we might have?

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any

**Comment by martukas** [comment]
Increasing hole sizes seems reasonable.

**Comment by martukas** [comment]
Implemented in #1159
