### ISSUE TITLE
Nuts on acrylic is hard to assemble and dissasamble

### ISSUE THREAD

**Issue by gokcemay** [RespiraWorks/Ventilator#1127]
Please take the time to describe the issue in detail, so that other contributors can pick it up and implement or declare it done/obsolete in case it was fixed out of band.

**Current behaviour/situation**
* Acrylic panel has to be assembled and disassembled a few times to test the build. They are on acrylic, thus bolts have to be inserted from under the internal tray. There isn't a lot of space there.

**Expected state/behaviour**
* Acrylic and internal tray CAD files

**How do you know it is wrong**

Assembling the enclosure and tray showed it is hard to dis/assemble.

Link to requirements or risk analysis if applicable.

**Starting points**
A solution is to move nuts to internal tray. Another solution is to use the design as it is but put bolts from top. Thus use those bolts as indexing pins.

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any

**Comment by martukas** [comment]
Not totally clear on which ones are the problem. Can we have some pictures to illustrate?

**Comment by martukas** [comment]
Implemented in #1159
