### ISSUE TITLE
Build GUI with CMake

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1180]
**What has to be done**
Switch over the build toolchain of the GUI to use CMake instead of QMake. It appears that this is possible, as a cursory web search reveals a number of pages that talk about how to do this, at least in principle... for example from Qt themselves:
https://doc.qt.io/archives/QtQuickCompiler/qquickcompiler-building-with-cmake.html

Resulting functionality should not change, only how the makefiles are generated.

**How do you know it has to be done**
While QMake is relatively capable at doing "usual" things, we are trying to be quite rigorous with all our test coverage and static check requirements. QMake is just not as flexible at specifying various compiler settings at different scopes, for example - adding some include paths for third-party liberaries with `-isystem` only to suppress static checks on code we did not ourselves write, or perhaps silencing specific checks on that code. This is where a more mature and flexible system like CMake would come in useful.

**Don't forget**
- [ ] Put the issue in a milestone
- [ ] Assign it to one of the projects
- [ ] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

**Comment by asmodai27** [comment]
Closed since #1185
