### ISSUE TITLE
no operator "/" matches these operandsC/C++(349)

### ISSUE THREAD

**Issue by EnziinSystem** [RespiraWorks/Ventilator#1195]
I see messages warning/error in the test file:
```
no operator "/" matches these operandsC/C++(349)
```
It happens in all test files, please view the attached file.

![cpp](https://user-images.githubusercontent.com/25495466/149661108-d1bb0c43-6b40-49aa-ad90-cb5657289cc3.png)

**Comment by asmodai27** [comment]
Hello

This message comes from the IDE not recognizing the includes in platformio.ini file.
When running the tests with platformio, the files are properly recognized, and (if it is the first time) platformio actually adds the proper includepath to the VScode environment, so this kind of error should disappear.

**Comment by asmodai27** [comment]
Solution given above works on a fresh install of VSCode.
