### ISSUE TITLE
Design of back panel acrylic for v0.4

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1248]
**What is required**

The back-panel acrylic plate has a basic outline and a few basic features already modelled in Inventor. We should finalize it to include all of the following (in rough order of priority):

* [x] #1040 
* [x] #961 
* [x] #1280 
* [x] #1281
* [x] #646
* [x] #1061 

Placement of all parts should observe where each of these connections will run to on the PCB or in the pneumatic system, to avoid wire harnesses being run in some awkward way or getting tangled.

**Starting points**
Existing Inventor model is a decent starting point.

**Comment by martukas** [comment]
May also be impacted by #1254

**Comment by zombiewater** [comment]
were going to add a part for the switch made of this thinner acrylic https://www.mcmaster.com/8560K191/

**Comment by martukas** [comment]
#1318 completes this task, the 2 constituent sub-tasks that remain open can be worked-on and solved orthogonally.
