### ISSUE TITLE
Can't add myself user to issue.

### ISSUE THREAD

**Issue by Felixea** [RespiraWorks/Ventilator#1314]
There is noassigne yourself button. What should I do?  

the link: https://github.com/RespiraWorks/Ventilator/issues/1198

**Comment by inceptionev** [comment]
If member is not yet invited, they cannot assign themselves to a ticket.  New users will need to request to an admin to be invited first.  Is this the intended behavior for the repo?

**Comment by inceptionev** [comment]
checked with Martin, this is the desired setting.
