### ISSUE TITLE
Umbrella issue: add clang-tidy checks

### ISSUE THREAD

**Issue by jkff** [RespiraWorks/Ventilator#132]
**What has to be done**
clang-tidy is a very useful tool for detecting bad patterns in code, such as code that is bug-prone or poorly readable. It has an extensive array of checks, and we should automate audit of our code for compliance with those checks - disallow submitting code that is non-compliant.

Note that some of the checks are overly strict (e.g. prohibit using `0xFF` because it is a "magic constant"), but clang-tidy is configurable. We should enable all checks, but disable those that are not useful.

This issue can be closed when:
* `./test.sh` directly or indirectly runs a configurable set of clang-tidy checks and this works correctly and in the same way on our CI and locally on contributor machines.
* The checks produce warnings worth fixing, and don't produce noise (warnings that have to be suppressed)

**How do you know it has to be done**
* From my day job experience, clang-tidy frequently catches major bugs
* clang-tidy can enforce naming conventions, which would help us establish a consistent code style

**Code pointers**
https://github.com/RespiraWorks/VentilatorSoftware/pull/130 adds a minimal check. The current bug is to enable more checks and bring code in compliance with them.
`test.sh` is the script that runs all tests/checks, both locally and on Travis
`.travis.yml` contains Travis configuration.
`.clang-tidy` is the clang-tidy config.

**Comment by martukas** [comment]
This has been partly addressed in #877 .
What remains:
* Will CI will have to be enabled when most of the existing errors are fixed. This has to do with refactoring/replacing `sprintf` as in #358 and a few others.
* Enabled more checks, rinse and repeat.

#117 (reformatting for style) is now unblocked
#885 should also enabled this for GUI code
