### ISSUE TITLE
Speed up gui-build-image CircleCI task

### ISSUE THREAD

**Issue by jlebar** [RespiraWorks/Ventilator#279]
Perhaps this is aspirational, but I noticed that the gpu-build-image CircleCI task takes 8.5 minutes to run.

https://circleci.com/gh/RespiraWorks/VentilatorSoftware/1587?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I was wondering if we could make this any faster?  @hhff @twslankard

**Comment by martukas** [comment]
`gpu-build-image` is no longer a thing since we are not dockerizing anything
