### ISSUE TITLE
Configure testing on additional toolchains

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#32]
Should build on other toolchains or platforms, i.e.: clang, ubuntu, windows, android?
Some of these are easily accessible on Travis at little additional cost. Different compilers might reveal different elusive errors.

**Comment by hhff** [comment]
On it @martukas

**Comment by martukas** [comment]
We have settled on a set of platforms that are relevant to our product and this additional scope is of marginal value.
