### ISSUE TITLE
Implement audio system for the alarms

### ISSUE THREAD

**Issue by tapemaster** [RespiraWorks/Ventilator#371]
**What has to be done**
Develop an API for alarms to emit sounds.

**How do you know it has to be done**
@Miceuz mentioned that this granular task can be implemented independently from the rest of alarms chunk.

**Code pointers**
// TODO

**Other**
#306 #370

**Comment by neelfirst** [comment]
Does this apply to the controller buzzer or the HDMI screen with speakers?

**Comment by martukas** [comment]
I think we have both the controller buzzer and the GUI HDMI sounds working.
