### ISSUE TITLE
Store hardware serial numbers in non-volatile storage.

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/Ventilator#376]
Please take the time to describe the issue in detail, so that other contributors can pick it up and implement or declare it done/obsolete in case if was completed out of band.

**What has to be done**
Demonstrate the recording of hardware serial numbers in EEPROM, OTP, or similar non-volatile storage.

**How do you know it has to be done**
Follow up from https://github.com/RespiraWorks/pcbreathe/issues/31. It is more expedient to serialize in software than hardware.

**Code pointers**
Give some thoughts on roughly where in code do you think the necessary changes might be located.

**Other**
Link the issue with a milestone, add appropriate labels, and mention dependent/blocked issues if any.

**Comment by sglow** [comment]
This information can be stored in the flash memory of the STM32, or in the small OTP memory area as long as we definitely don't want to ever change it.

**Comment by martukas** [comment]
@asmodai27 implemented non-volatile storage. There is memory reserved for unit serial, but it needs to be entered manually. Maybe this could be part of the deployment scripts for when the vent is run for the first time.

**Comment by asmodai27** [comment]
We could run a sanity check in the debug scripts, which identify the serial number during initial communication with the controller, and ask the user to specify a value if the serial number is 0 (default value)
On a slightly different note, we may want to store alphanumerical values instead of simply a number.
