### ISSUE TITLE
Work on software architecture document

### ISSUE THREAD

**Issue by lee-matthews** [RespiraWorks/Ventilator#51]

**Comment by neelfirst** [comment]
@lee-matthews  I know you've put in a lot of work into this. Can you add a link here? What remains to be done? Can I get you some assistance? Thanks.

**Comment by lee-matthews** [comment]
https://docs.google.com/document/d/1FPB31V72r_keu1_xjUfYCUXGLxBC5hoyCT1naPNNNTA/edit

Please feel to get someone to work on it :)

**Comment by asmodai27** [comment]
Like I said on slack, I started a document on my end that describes the inner workings of the controller: https://docs.google.com/document/d/e/2PACX-1vQ5zpzNkm-p2jS8UI1QRwzOUAeX9tz00BAQlaYabDSOTT4NmYzgVcRgcdrfjCxeNCBpx-gVNb8adOCK/pub

If this is the kind of things you had in mind, feel free to add it to the architecture document.

**Comment by tapemaster** [comment]
This has been worked on :P
