### ISSUE TITLE
Work on software requirements

### ISSUE THREAD

**Issue by lee-matthews** [RespiraWorks/Ventilator#52]

**Comment by neelfirst** [comment]
@lee-matthews  I know you've put in a lot of work into this. Can you add a link here? What remains to be done? Can I get you some assistance? Thanks.

**Comment by neelfirst** [comment]
question: should https://github.com/innolitics/rdm be brought in as a submodule

**Comment by burnhamd** [comment]
@neelfirst no.  it isn't required for the repo.  It should be setup as a python requirement for anyone who intends to modify the documents or make a release

**Comment by martukas** [comment]
We have migrated SW reqs to Valispace and people have definitely worked on them.
