### ISSUE TITLE
ansible playbook should install necessary GUI packages

### ISSUE THREAD

**Issue by twslankard** [RespiraWorks/Ventilator#539]
* Install packages that permit GL acceleration (can be determined by running sudo raspi-config and then enabling GL when these packages haven't been installed already.)
* Install lightdm
* Install openbox
* enable auto-login

**Comment by martukas** [comment]
Has there been progress on this? I see an ansible playbook in the repo under `software/gui/rpi-image`

**Comment by martukas** [comment]
We are no longer doing VM deployment, so this is no longer relevant.
