### ISSUE TITLE
FiO2 sensor selection

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/Ventilator#637]
Right now we are stuck with galvanic cell O2 sensing which is more widely available but degrades quickly (12 months or faster if we use it in closed loop O2 control).

We would like to switch to oxygen fluorescence quenching but it is currently a supply chain risk.

**Comment by inceptionev** [comment]
Calling this done for now.  We have integrated this sensor into the design, and it is and will be moving forward with this.  If further testing deems a change needed a new ticket will be created.

**Comment by VSTheBestDeveloper** [comment]
This ticket was in the "Done" column in Hardware. Moved it to the same column after changing repositories.
