### ISSUE TITLE
spike: bypass leg architectural investigation (modelon)

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/Ventilator#639]
Bypass leg in pneumatic architecture modeled. Update models to proportional. The bypass leg should help the blower maintain a higher flow during exhale, so it doesn't have to spin up from stall during inhale.

**Comment by martukas** [comment]
Some words on why we decided against this and we can close this?

**Comment by inceptionev** [comment]
During the control design leading up to CoVent demo, we determined that we could achieve the required overshoot performance without the need for a bypass leg.  See CoVent data.
