### ISSUE TITLE
Design battery backup circuit

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/Ventilator#642]
There is definitely a reference to battery backup circuitry. Presumably we are using 12V SLAs but deciding where in the circuit they go and how to handle power crossover are open items.

**Comment by VSTheBestDeveloper** [comment]
@inceptionev - Is this still relevant? Can the issue be moved into Done?

**Comment by inceptionev** [comment]
@VSTheBestDeveloper this is still in work, will be implemented by PR #951
