### ISSUE TITLE
Move Beta BOM to 3/4" tubing 

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/Ventilator#650]

**Comment by DonnaCG** [comment]
To be reviewed post enclosure build

**Comment by martukas** [comment]
This is basically done, other than segments of tubing that are part of pinch valve assemblies.

**Comment by VSTheBestDeveloper** [comment]
This ticket was Closed in the Hardware project. Moved it to Mechanical and Pneumatics and closed it.
