### ISSUE TITLE
Create CI job to check for dead links on this repo

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#691]
Master branch is now restricted. PRs required to change content. We need a CI job to check for broken links when committing and/or doing PR.

**Comment by martukas** [comment]
After merging repos this may need additional work to ensure all jobs are performed. @jlebar you got this or need help?

**Comment by martukas** [comment]
@a-vinod has set this up and it's been working for a while

**Comment by VSTheBestDeveloper** [comment]
This ticket was in the "Done" column in Hardware. Moved it to the same column after changing repositories.
