### ISSUE TITLE
Support persistent storage

### ISSUE THREAD

**Issue by tapemaster** [RespiraWorks/Ventilator#712]
We need to store the latest ventilator settings on the storage which survives power disconnect.
Options:
1. Doing it on the flash of STM32 would make the processor stop for a short time because the program memory and data memory are on the same flash bank.
2. Get another version of STM32 with dual flash banks.
3. Add an EEPROM on the PCB, this will not pause the STM32 when it needs to write/read something there.

Currently the preferable option is number 3.

**Comment by jlebar** [comment]
Specifically, we're ok with (1) if and only if we don't have to write anything while the vent is hooked up to a patient.

**Comment by jlebar** [comment]
Related: https://github.com/RespiraWorks/VentilatorSoftware/issues/376
https://github.com/RespiraWorks/VentilatorSoftware/issues/170

**Comment by tapemaster** [comment]
@inceptionev can you please known details about EEPROM here?

**Comment by inceptionev** [comment]
This is the current selected i2c EEPROM:https://ww1.microchip.com/downloads/en/DeviceDoc/24AA256-24LC256-24FC256-Data-Sheet-20001203W.pdf
