### ISSUE TITLE
Add +5 aux power (for touchscreen display)

### ISSUE THREAD

**Issue by KennethLaws** [RespiraWorks/Ventilator#730]
Touchscreen may require too much power for hdmi interface.  Adding an aux +5 would be good practice even if not absolutely needed

**Comment by dcstraney** [comment]
Raspberry Pi has its own +5V supply as of #939 and this has a couple amps to spare for a touchscreen or other.  No idea how much the touchscreen may need though (the aliexpress page doesn't have any detailed specs I can find on current draw).

**Comment by inceptionev** [comment]
implemented by #1101
