### ISSUE TITLE
Evaluate form factor for RPI

### ISSUE THREAD

**Issue by KennethLaws** [RespiraWorks/Ventilator#732]
Current form factor may have more interfaces than we need.  Evaluate using something like standard DDR2 SODIMM form factor, e.g., 
Mfr. Part #: CM3+/32GB
Allied Stock #: 71555194
Save money, space, widely available, some added design cost and connectors to add.

**Comment by inceptionev** [comment]
decided to stay with the current rpi4 for availability issues, implemented on #1101
