### ISSUE TITLE
Bring 3x Stepper Modules onto the board

### ISSUE THREAD

**Issue by inceptionev** [RespiraWorks/Ventilator#733]
We originally had this as an optional module that could be plugged into the Nucleo board on this setup:https://www.st.com/en/ecosystems/x-nucleo-ihm03a1.html

We now want to have this driver chip directly on the board.  The documentation for this module, including schematic are in the link above.  The modules are designed to stack up to 3-high, with some resistor placement options to allow all three to be addressed on a single SPI bus.  This 3-stack implementation is what we want to emulate on our board.

**Comment by KennethLaws** [comment]
this issue should be connected to issue 733 steppers on pcb

**Comment by martukas** [comment]
This issue looks like a duplicate of #773. Is has this been superseded by that ticket and can be closed?

**Comment by KennethLaws** [comment]
I believe the answer is yes

**Comment by inceptionev** [comment]
closed by pr #1033
