### ISSUE TITLE
Rev 1.0 PCB: DNP components are stuffed

### ISSUE THREAD

**Issue by inceptionev** [RespiraWorks/Ventilator#739]
@sglow discovered 5V on the CC-3V3 rail. Looks like this is because JLCPCB stuffed many of the DNP components in the BOM. Fix: remove R2, R73, R75, R77. R67, R17, R18, R59, R60, R68, R69

**Comment by dcstraney** [comment]
No longer relevant to "clean start design" for Rev. A; will be careful about DNP markers in BOM.
