### ISSUE TITLE
Level translator design causes blower to go full throttle on reset

### ISSUE THREAD

**Issue by inceptionev** [RespiraWorks/Ventilator#740]
The level translator is an open-drain design so it gives a command-high (full throttle) command to the blower when the STM32 goes into high-Z state during programming.  This is obviously an undesired behavior and should be fixed in the next rev by switching to a push-pull level translator with an input pull-down.

**Comment by dcstraney** [comment]
Fixed in #947 by copying non-inverting level translator from FoundryM design.
