### ISSUE TITLE
Motor needs 5V command but STM32 is 3.3V GPIO out

### ISSUE THREAD

**Issue by inceptionev** [RespiraWorks/Ventilator#745]
will need a level shifter

**Comment by dcstraney** [comment]
New level shifter implemented in #947 by copying non-inverting level translator from FoundryM design.

**Comment by inceptionev** [comment]
Rework instructions for adapting Rev 1.0 PCB:

- Obtain [sparkfun level translator board BOB-12009](https://www.sparkfun.com/products/12009)
- Solder the following connections on the bottom side of the board:
  - PCB P2.16 - BOB LV
  - PCB P3.31 - BOB LV2 
  - PCB J5.1 - BOB HV
  - PCB J5.2 - BOB HV2
  - PCB J5.3- BOB GND
  - Stake the wires to keep them from moving.
  - Attach the BOB to board with two-sided adhesive tape.
 ![image](https://user-images.githubusercontent.com/8660661/109103005-db5c2b00-76de-11eb-83dc-b67c13b0f1c6.png)
 - Cut the BLOWER_CTRL trace on the top side of the board as shown:
![image](https://user-images.githubusercontent.com/8660661/109102650-2cb7ea80-76de-11eb-9257-9cb9310a04dc.png)

![image](https://user-images.githubusercontent.com/8660661/109103073-02b2f800-76df-11eb-8d95-8cf5300d978f.png)
