### ISSUE TITLE
Need external flash chip on next board

### ISSUE THREAD

**Issue by sglow** [RespiraWorks/Ventilator#747]
We can't save data to the STM32 internal flash chip during ventilator operation because doing so could significantly impact the control loop performance.
Adding a small external flash chip is probably the simplest and cheapest solution to this problem.
We don't need a lot of memory.  256kbit would be more then enough to store parameter values.  There are lots of options on digikey for 8-pin SPI flash chips of this size for under $0.50.
It's possible that we won't even need this functionality, but having a spot for an external flash chip on the board would give us the option.

**Comment by dcstraney** [comment]
Implemented with 24LC256 I2C EEPROM in #947 as copied from FoundryM design.
