### ISSUE TITLE
Replace Nucleo board with STM32 chip

### ISSUE THREAD

**Issue by sglow** [RespiraWorks/Ventilator#754]
The Nucleo board really doesn't have much on it that's useful other then the STM32 part.  Why not just place the part down on this board and get rid of the Nucleo board all together?  That would lower cost and put us one step closer to a final design which certainly won't include that board.
The Nucleo board does have a debug interface which is handy, but that can be replaced with a 4 pin connector to allow an external STLINK debugger to be connected to the chip.
Other then the processor and the debugger, the Nucleo board is pretty much just connectors and power supplies.

**Comment by dcstraney** [comment]
Implemented as of #1004
