### ISSUE TITLE
Provide separate voltage regulators for subsystems

### ISSUE THREAD

**Issue by Miceuz** [RespiraWorks/Ventilator#756]
Not sure how much of this is necessary, but I have had good experience providing a separate regulator for separate subsystems, in this case Arduino, Raspi and monitor. Note, Arduino handles sensors and might benefit from better rail ripple figures.

**Comment by dcstraney** [comment]
#939 adds separate +5V for RPi, and separate +3.3V for STM32 and digital control vs. +3.3V for sensors.
