### ISSUE TITLE
Collect power consumption information

### ISSUE THREAD

**Issue by inceptionev** [RespiraWorks/Ventilator#766]
Collect power consumption information in the following conditions:

Input power: 12V

 - Fully on (all actuators running)
 - All actuators off, but with GUI+Controller+Touchscreen running

**Comment by inceptionev** [comment]
- Fully on (21% oxygen, air only): 3.7A (44.4W)

Note: we don't currently have a mode that runs both the oxygen PSOL and the blower at the same time, so this consumption has to be estimated:

- With full current on the PSOL as well +400mA @ 12V: 4.1A total (49.2W)
- All actuators disconnected, computing only, i.e. UI Computer, Controller, and Touchscreen on only: 0.77A (9.24W)

**Comment by KennethLaws** [comment]
This is great. Thanks!

Sent from my iPhone

On Jul 1, 2020, at 3:25 PM, Edwin Chiu <notifications@github.com> wrote:

﻿
LEARN FAST: This email originated outside of HERE.
Please do not click on links or open attachments unless you recognize the sender and know the content is safe. Thank you.


  *   Fully on (21% oxygen, air only): 3.7A (44.4W)

Note: we don't currently have a mode that runs both the oxygen PSOL and the blower at the same time, so this consumption has to be estimated:

  *   With full current on the PSOL as well +400mA @ 12V: 4.1A total (49.2W)
  *   All actuators disconnected, computing only, i.e. UI Computer, Controller, and Touchscreen on only: 0.77A (9.24W)

**Comment by inceptionev** [comment]
Task completed, closing ticket
