### ISSUE TITLE
Complete 0.3 enclosed build

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#774]
**What has to be done**
This is a collector issue - for all tasks under enclosure build.
This encompasses the building of two complete prototypes, one in Maryland and one in California.
The sub-issues for each build are as follows:

| Component | MD build ticket | CA build ticket |
|---|---|---|
| back panel | #785 | #786 |
| filter panel | #790 | #791 |
| display panel | #788 | #789 |
| pneumatics | #781 | #782 |
| main enclosure | #783 | #784 |
| final integration | #792 | #793 |

**How do you know it has to be done**
Design review of beta build is completed, all lesson learned identified and issues/actions identified (in Git)
#787 

**Other**
Tasks to be identified to support enclosure build.
[20200708-Respiraworks V3 Enclosure Package (1).zip](https://github.com/RespiraWorks/Ventilator/files/4933171/20200708-Respiraworks.V3.Enclosure.Package.1.zip)

**Comment by DonnaCG** [comment]
Enclosure ordered - July 24th with PegaPrecision.  Enclosure manufacturing to be completed August 21.

**Comment by martukas** [comment]
All constituent tickets are closed. This umbrella issue is therefore also done.
