### ISSUE TITLE
Relocation of Power & Oxygen input on enclosure

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#776]
**What has to be done**
Review to see move power & Oxygen reconfig is required prior to enclosure fabrication.

**How do you know it has to be done**
Feasibility study is completed.

**Comment by tijanim** [comment]
- Investigate moving O2 Hardware to underneath shelf
- Investigate moving O2 input port to side panel
- Add power port to side of panel.

**Comment by DonnaCG** [comment]
Since these changes will not be included in Beta Build, we should move task to Reference Design or Gamma Build

**Comment by martukas** [comment]
This is partly superseded by #965 (power equipment placement)
O2 related questions still stand

**Comment by martukas** [comment]
Oxygen input through-fitting is now on the newly created back panel.
DIN power input is now on the newly created back panel.

This among the checked-in changes addressing #957 

![image](https://user-images.githubusercontent.com/1972005/113712689-6eac5700-96b4-11eb-8e9a-6043206b9679.png)
