### ISSUE TITLE
Cut acrylic panels for 0.3 enclosed build

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#777]
**What has to be done**
Identify place to cut Acrylic, Cut Acrylic Panel,
Acrylic available in Oakland
Then ship to Maryland (Martin)

**Comment by inceptionev** [comment]
Edwin to talk to Momentum to find out what files are needed
Donna to talk to Randall and Tijani to get the drawings.

**Comment by martukas** [comment]
acrylic panels for enclosed 0.3 builds were manufactured and received by @martukas and @inceptionev
