### ISSUE TITLE
Ordering parts for 0.3 build

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#778]
**What has to be done**
After BOM Scrub completed, order components for beta build.
Assumes all components from McMaster.
Request any 3D printed parts needed from the team.

**Comment by DonnaCG** [comment]
Please see updated BOM that highlights who needs to order what.  
Green = Martin to order
Blue = Edwin to order

**Comment by martukas** [comment]
parts for enclosed 0.3 builds were received by @martukas and @inceptionev
