### ISSUE TITLE
Build 0.3 enclosed ventilator - pneumatics equipment panel - location MD

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#781]
Assemble all components to Pneumatics Equipment Panel.
Document any issues/improvements identified during build.

This is 1 of 2 Ventilator Beta Builds

- 

Assumption - to be completed by Martin.

**Comment by martukas** [comment]
This is nearly done, pending modifications for oxygen and overpressure relief valve.

**Comment by martukas** [comment]
Sister ticket for CA build #782

**Comment by martukas** [comment]
![image](https://user-images.githubusercontent.com/1972005/108945184-236d4600-762a-11eb-9731-e52d2fdab353.png)
