### ISSUE TITLE
Build 0.3 enclosed ventilator - pneumatics equipment panel - location CA

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#782]
Assemble all components to Pneumatics Equipment Panel.
Document any issues/improvements identified during build.
This is 2 of 2 Ventilator Beta Builds

**Comment by martukas** [comment]
Sister ticket for MD build #781

**Comment by inceptionev** [comment]
Build notes.

- Pinch valve hole patterns do not line up properly
- Pinch valve stepper motor cutouts needs enough gap for the wires to pass through during assembly.  Consider cutting a notch.
- Stepper wires needs a place to route up the the PCB
- Blower adapter does not retain gasket, makes it hard to keep it in place during blower stack assembly.
- Holes in the plates for the blower do not clear the screws, needed to be reamed.
- Mounting nuts from the back side for the oxygen regulator is pretty awkward, maybe consider using melt-in nuts?
- Check valve pressure drop seems pretty high.

**Comment by inceptionev** [comment]
Build complete
