### ISSUE TITLE
Build 0.3 enclosed ventilator - main enclosure - location MD

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#783]
Assemble all components to Main Enclosure.
Document any issues/improvements identified during build.

This is 1 of 2 Ventilator Beta Builds

**Comment by martukas** [comment]
Sister ticket for CA build #784

**Comment by martukas** [comment]
![image](https://user-images.githubusercontent.com/1972005/108945349-76df9400-762a-11eb-9881-f826f1c54295.png)
