### ISSUE TITLE
Build 0.3 enclosed ventilator - main enclosure - location CA

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#784]
Assemble all components to Main Enclosure.
Document any issues/improvements identified during build.

This is 2 of 2 Ventilator Beta Builds

**Comment by martukas** [comment]
Sister ticket for MD build #783

**Comment by inceptionev** [comment]
Build notes

Flex in the internal frame makes it hard to line up some of the screws for closure.

Build complete
