### ISSUE TITLE
Build 0.3 enclosed ventilator - back panel - location MD

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#785]
Assemble all components to Back Panel.
Document any issues/improvements identified during build.

This is 1 of 2 Ventilator Beta Builds

**Comment by martukas** [comment]
Sister ticket for CA build #786

**Comment by martukas** [comment]
![image](https://user-images.githubusercontent.com/1972005/108945496-b4442180-762a-11eb-9594-eaf4aaa9c034.png)
