### ISSUE TITLE
Design review for 0.3 enclosed build

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#787]
Hold Beta Build Design Review
After beta build is completed (both builds, east & west, a design review shall be scheduled to review the following.)
- identify all issues raised in beta build (raise tickets as req'd)
- share lessons learned
- identify next steps for next iteration of build

**Comment by martukas** [comment]
2 enclosed builds were completed, as documented in #774 
and tickets were created to address various issues, which have been captures in milestones for the succeeding prototype in the following milestones:
* v0.4 enclosure: https://github.com/RespiraWorks/Ventilator/milestone/27
* v0.4 mechanical/pneumatics: https://github.com/RespiraWorks/Ventilator/milestone/29
