### ISSUE TITLE
Build 0.3 enclosed ventilator - display equipment panel - location MD

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#788]
Assemble all components to Display Equipment Panel.
Document any issues/improvements identified during build.

This is 1 of 2 Ventilator Beta Builds

**Comment by martukas** [comment]
Sister ticket for CA build: #789

**Comment by martukas** [comment]
![image](https://user-images.githubusercontent.com/1972005/108945002-d38e7f00-7629-11eb-8796-5bdd22a8a0f2.png)
![image](https://user-images.githubusercontent.com/1972005/108945024-db4e2380-7629-11eb-9b59-e54eec0f5113.png)
