### ISSUE TITLE
Build 0.3 enclosed ventilator - display equipment panel - location CA

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#789]
Assemble all components to Display Equipment Panel.
Document any issues/improvements identified during build.

This is 2 of 2 Ventilator Beta Builds

**Comment by martukas** [comment]
Sister ticket for CA build: #788

**Comment by martukas** [comment]
@inceptionev posted this in the mechanical channel:
"here’s how my PCB is mounted.  The screen has bosses for mounting an RPi.  I put standoffs into the bosses, then the PCB on top, with the long RPi standoffs now running through the PCB into the standoffs on the screen.  The the Pi just mounts on top of that."

![image](https://user-images.githubusercontent.com/1972005/107089801-392ae080-67cd-11eb-9583-a330b1be1f8b.png)
![image](https://user-images.githubusercontent.com/1972005/107089827-421bb200-67cd-11eb-8468-94464bacc5dc.png)
![image](https://user-images.githubusercontent.com/1972005/107089841-4a73ed00-67cd-11eb-9d9c-2f92b563e053.png)

**Comment by inceptionev** [comment]
Build notes:

- Nucleo USB programming port is hard to access.

Build complete.
