### ISSUE TITLE
Build 0.3 enclosed ventilator - filter equipment panel - location MD

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#790]
Assemble all components to Filter Equipment Panel.
Document any issues/improvements identified during build.

This is 1 of 2 Ventilator Beta Builds

**Comment by martukas** [comment]
Sister ticket for CA build: #791

**Comment by martukas** [comment]
![image](https://user-images.githubusercontent.com/1972005/108942756-90321180-7625-11eb-999e-76913b00f327.png)
