### ISSUE TITLE
Build 0.3 enclosed ventilator - filter equipment panel - location CA

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#791]
Assemble all components to Filter Equipment Panel.
Document any issues/improvements identified during build.

This is 2 of 2 Ventilator Beta Builds

**Comment by martukas** [comment]
Sister ticket for MD build: #790

**Comment by inceptionev** [comment]
Notes from build:

- Filter plate holes do not clear M4 screws
- Filter plate assembly causes curvature/warping of acrylic plate.
- Would prefer if panels were fixed to tray so that they can be removed as once piece (as opposed to sandwiched in between tray and enclosure.

Build complete.
