### ISSUE TITLE
Build 0.3 enclosed ventilator - final integration and wiring - location MD

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#792]
Assemble all components in enclosure build, including final integration of all components and wiring.
Document any issues/improvements identified during build.

This is 1 of 2 Ventilator Beta Builds

**Comment by martukas** [comment]
Sister ticket for CA build: #793

**Comment by martukas** [comment]
![image](https://user-images.githubusercontent.com/1972005/108945583-d63da400-762a-11eb-83d4-6d5143f90500.png)
