### ISSUE TITLE
Build 0.3 enclosed ventilator - final integration and wiring - location CA

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#793]
Assemble all components in enclosure build, including final integration of all components and wiring.
Document any issues/improvements identified during build.

This is 2 of 2 Ventilator Beta Builds

**Comment by martukas** [comment]
Sister ticket for MD build: #792

**Comment by inceptionev** [comment]
notes from build:

 - Nucleo USB programming port not very accessible.
 - Tray frame doesn't come out of enclosure easily, some interference issues with mounting tabs.

build complete.
