### ISSUE TITLE
Move Requirements & Glossary wiki pages into repo

### ISSUE THREAD

**Issue by gracecanfield** [RespiraWorks/Ventilator#796]
https://github.com/RespiraWorks/Ventilator/wiki/Requirements
https://github.com/RespiraWorks/Ventilator/wiki/UI-Requirements
https://github.com/RespiraWorks/Ventilator/wiki/Using-Valispace
https://github.com/RespiraWorks/Ventilator/wiki/Ventilator-Glossary

**Comment by martukas** [comment]
Done
