### ISSUE TITLE
Incorporate CoVent assembly instructions content into repo documentation

### ISSUE THREAD

**Issue by gracecanfield** [RespiraWorks/Ventilator#801]
The following files have been brought into the repo as PDFs:
`design/assets/covent-june-2020-design-overview-document.pdf`
`design/assets/covent-june-2020-progress-status-report.pdf`
`manufacturing/assets/covent-june-2020-assembly-instructions.pdf`
`manufacturing/assets/covent-june-2020-production-methods-for-custom-components.pdf`

The content should be migrated into the repository as **plain text in markdown** and **discrete graphics files**, so that the content can be version controlled and improved upon instead of frozen in an opaque and unbrowsable form that is the PDF.

The word docs from which all of these were generated are found [here](https://drive.google.com/drive/folders/1o4Kr_9_fYovlg636wIGeBFWF83NUe6za?usp=sharing)

**Comment by martukas** [comment]
This is done, as tagged in all the of the commits above.
