### ISSUE TITLE
Migrate requirements from Valispace into github

### ISSUE THREAD

**Issue by gracecanfield** [RespiraWorks/Ventilator#803]

**Comment by martukas** [comment]
We might instead want to migrate all requirements out of Valispace, since no one loves it and we want things as openly accessible as possible

**Comment by martukas** [comment]
Which is something we will want to do after #250 gets merged.

**Comment by dheater** [comment]
Relates to #52

**Comment by dheater** [comment]
@martukas @inceptionev Do we want to migrate the [Covent-19 Specification](https://covent-19.valispace.com/project/34/specifications/groups/13/requirements) or are they obsolete?

**Comment by martukas** [comment]
yeah, we don't care about that specification anymore

**Comment by dheater** [comment]
I imported them earlier today since they were linked to the system requirements, but we can pull them out if that's preferable.  Let's discuss in the PR #1086
