### ISSUE TITLE
Document 0.3 build enclosure

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#810]
**Folder/Page:**
There should be a page for the beta build enclosure. Somewhere under beta, I guess.

**Task:**
Get this info from Randall and Tijani and Donna, possibly? some of this was discussed in one of the #eng- channels.
There were discussions about what angle things should be bent at and how that informed selection of manufacturer. Any of this stuff that impacts knowing how to properly get it made should be somehow documented. What sort of machine is needed for cutting the acrylic stuff? Maybe links to some companies that are good candidates for getting it done? But fundamental criteria for selection would be better.

**Subtasks:**
* [ ] CAD files for sheet metal stuff
* [ ] CAD files for acrylic stuff

**Relevant files:**
Probably exported from Fusion or whatever they are using.

**Comment by martukas** [comment]
Not sure if this was broken out into sub-tasks, but this probably entails just migrating the CAD and drawings for metal and acrylic to Inventor?

**Comment by tijanim** [comment]
This is now contained in #937

**Comment by tijanim** [comment]
and somewhat by drawings done in #943

**Comment by martukas** [comment]
Superseded by other tickets mentioned above.
