### ISSUE TITLE
Add an absolute pressure sensor to determine altitude

### ISSUE THREAD

**Issue by inceptionev** [RespiraWorks/Ventilator#814]
We will probably want some kind of absolute pressure sensor on the PCB.  There are some self-checks that will behave differently at altitude and we can't rely on the clinician to know what the altitude of the hospital is and punch it in.

BMP280 is a likely candidate and we can hang it off the i2c bus.

https://www.digikey.com/product-detail/en/bosch-sensortec/BMP280/828-1064-1-ND/6136315

**Comment by dcstraney** [comment]
Added to schematic as of #947.  BMP280 selected by default but other I2C devices can be substituted if necessary.
