### ISSUE TITLE
Risk: Inlet Filter Drops Blower Performance

### ISSUE THREAD

**Issue by inceptionev** [RespiraWorks/Ventilator#815]
We need to do a characterization test to demonstrate that the ventilator has acceptable performance with the filters in the flow path.

In particular, the inlet filter is a concern because we have not had a proper inlet assembly to adapt to a filter until now.

Task: use the PAPR inlet assembly to add a filter to the inlet and run the CoVent test set and record the data.

**Comment by HariGanesh-27** [comment]
Alternatively, I propose that we use the same filter housing (3D printed filter housing) to do the tests and conclude on performance changes.

**Comment by inceptionev** [comment]
I can use the same filter housing, I just need the inlet assembly from the PAPR to connect it to the blower inlet.

**Comment by inceptionev** [comment]
I ran a test with all 4 filters installed and little impact on performance was observed, and pip targets up to 35cm were achieved on 1s i-time and 50ml/cmH2O compliance.  The immediate risk of a drastic change in performance is retired.  At a future date, when the full enclosed vent is built, a new baseline performance dataset will be generated.

Ticket OK to close.
