### ISSUE TITLE
Publish BOM for enclosed 0.3 build to git

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#820]
**What has to be done**
After Beta Build is completed, BOM should be review and updated according to findings from Beta Build.
Final list to be issued to Git for revision control.

**Comment by martukas** [comment]
I think most of the BOM is in various sub-assembly pages, so this ticket might be re-scoped as either duplicating that as a complete all-inclusive BOM or just auditing the various pages to make sure nothing is missing.

**Comment by tijanim** [comment]
This is now contained in #937

**Comment by martukas** [comment]
#1035 ensures that all salient parts are listed in sub-assembly pages. A complete BOM may still have to be generated, but this will be the outcome of a more permanent and automated solution for BOM management as outlined in #1011
