### ISSUE TITLE
Review Parts Inventory - preparation for beta build

### ISSUE THREAD

**Issue by DonnaCG** [RespiraWorks/Ventilator#821]
**What has to be done**
Review Pizza Build and identify current available inventory with Edwin.
Purpose of this exercise, is to identify missing parts to be ordered in preparation of Beta Build

**How do you know it has to be done**
All inventory columns are completed.

If the quantity identified in "needed" column is not correct, or not precise enough, just update accordingly.
https://drive.google.com/file/d/1vqoaHk_54RKiV9V2NL35gHngVxuSySWt/view?usp=sharing

**Comment by martukas** [comment]
This looks like a duplicate of #834

**Comment by inceptionev** [comment]
I think it's one for your inventory and one for mine, @martukas

**Comment by DonnaCG** [comment]
Yes I created two, one for each build.  But #775 is a duplicate.

**Comment by inceptionev** [comment]
Inventory complete
