### ISSUE TITLE
Ensure config data is within hard limits

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#83]
Subtask of #58 
Needs further explanation. How are these limits defined? Can we link to a specs document?
And most importantly, is this critical for Alpha?
@lee-matthews @neelfirst

**Comment by neelfirst** [comment]
It looks like #58 is beta so this should be beta as well. I'm not really sure what this means anyways.

**Comment by lee-matthews** [comment]
These are to validation check input values to be sure that they're within
safe limits. It's to stop someone inadvertently setting the respiration
rate to 1000 breaths/minute for example.

**Comment by tapemaster** [comment]
Implemented by having limits on GUI input widgets.
