### ISSUE TITLE
Generalize PID tuning parameters

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#867]
**What has to be done**
It should be possible to:
* manually tune blower valve gain without recompiling, in addition to using gain scheduling
* PID tuning should either be documented as a procedure, or, preferrably, be to some extent a scripted process

**How do you know it has to be done**
India had to do this, and Edwin had to write a branch with modified code just for this purpose.

**Code pointers**
Maybe this branch can be used as a starting point. TODO: Please link it here:

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

**Comment by inceptionev** [comment]
This is done, present in the master branch via the console interface
