### ISSUE TITLE
Setup Alpha Raspberry Pi Factory Image

### ISSUE THREAD

**Issue by hhff** [RespiraWorks/Ventilator#88]
- [ ] A light weight Raspbian Image 
- [ ] Runs docker
- [ ] It automatically runs the local cached image for `respiraworks/gui:latest`
- [ ] This Raspbian image should build in CI ideally

**Comment by hhff** [comment]
@twslankard to provide @a-vinod first ansible steps

**Comment by hhff** [comment]
Ansible is probably the move but this is the option: https://www.pibakery.org/

**Comment by martukas** [comment]
ansible and docker stuff no longer relevant
