### ISSUE TITLE
Add External Gauge Pressure Sensors to the rev 1 PCB

### ISSUE THREAD

**Issue by saipraveenpanchakarla** [RespiraWorks/Ventilator#880]
**What has to be done**
We are using MPX5700AP/GP/GP1
CASE 867B-04 gauge pressure sensor in the oxygen line with an alternative to the oxygen regulator. based on the input pressure from the gauge sensor we can proportionally control the solenoid valve. 

**How do you know it has to be done**
Due to oxygen regulator supply issues, we need to think alternative.

**Hardware pointers**
We think to use PC2, PC3 pins of cycle controller. we have a doubt that in the existing circuit we are using a scaling circuit. please suggest whether the same scaling, the filter circuit can be used for the gas sensor or not please suggest if any modifications

**Comment by inceptionev** [comment]
the need for this has been covered by moving to closed-loop nested flow control for oxygen in v0.4.  This allows us to control oxygen accurately without needing to know the source pressure.  This was implemented in the PCB hardware in #1101
