### ISSUE TITLE
Place  Interim Card on PCB

### ISSUE THREAD

**Issue by saipraveenpanchakarla** [RespiraWorks/Ventilator#891]
**What has to be done**
Place the Interim card to the next revision of PCB. 

**How do you know it has to be done**
Stepper drivers, Interim cards are now on shield boards on the STM32, need to replace all boards into rev a pcb.

**Hardware Pointers**
Need to replace all stack boards into the rev A PCB including STM32 Nucleo L-452RE Board.

**Comment by martukas** [comment]
Features of interim card have been incorporated into new PCB
