### ISSUE TITLE
Adding a Barb on the filter housing on the tube side.

### ISSUE THREAD

**Issue by RakurthiLokesh** [RespiraWorks/Ventilator#892]
**What has to be done**
A barb has to be added to the filter housing to hold the tube firmly as the tube is getting slipped from the filter housing.
Files of the new design should be updated in the repository:
* Original CAD files (or link to web-based CAD)
* exported stl or step files

**How do you know it has to be done**
While assembling the enclosure we faced an issue of the tube gets slipped off from the filter housing so form the next revision we are planning to add a barb on the housing so that it will help in holding the tube firmly.
![image](https://user-images.githubusercontent.com/68268508/92215610-b23aaa80-eeb2-11ea-8664-c90d15f0d3be.png)

**Code pointers**
This is the page that needs to be updated:
https://github.com/RespiraWorks/Ventilator/tree/master/manufacturing/filter_holder

**Comment by martukas** [comment]
Question about the shape of the barb. Could it not instead be like this type of barb that we have on most of tube fittings?
![image](https://user-images.githubusercontent.com/1972005/92225334-0e7cda80-ee71-11ea-9fd6-0ad6b865a478.png)

I am concerned that width of the "notch" must be compatible with whatever clip we use to attach the tubing, so this may be making too much of at assumption at this stage in prototyping?

**Comment by martukas** [comment]
This issue is superseded by #917
