### ISSUE TITLE
Blower Sub-Assembly

### ISSUE THREAD

**Issue by RakurthiLokesh** [RespiraWorks/Ventilator#905]
**What has to be done**
The air from the inlet HEPA filter should enter into the blower without any leakages, that can be achieved by using a specially designed adapter and gaskets placed at right places mounting with the help of Acrylic sheet pieces and screws.
![IMG_20200926_130922](https://user-images.githubusercontent.com/68268508/94338218-2974e180-000e-11eb-8334-39a503ef77c6.jpg)
![IMG_20200926_130926](https://user-images.githubusercontent.com/68268508/94338223-31cd1c80-000e-11eb-8c0a-7f64fb022a31.jpg)
![IMG_20200926_130909](https://user-images.githubusercontent.com/68268508/94338224-3396e000-000e-11eb-90d8-26d021fdc70d.jpg)
![IMG_20200926_130917](https://user-images.githubusercontent.com/68268508/94338227-3560a380-000e-11eb-9695-8d7c68c68c61.jpg)
**How do you know it has to be done**
There is no way to connect the tube to the Blower.
**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

**Comment by tijanim** [comment]
Superseded by #924
