### ISSUE TITLE
Migrate pinch valve to Inventor

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#927]
**What has to be done**
Pinch valve CAD should be migrated from OnShape to Inventor

**How do you know it has to be done**
It has been decided that we consolidate our CAD in in Inventor

**Code pointers**
All relevant links to get started should be here:
https://github.com/RespiraWorks/Ventilator/tree/master/manufacturing/pinch_valve

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

**Comment by tijanim** [comment]
@martukas I think #941 may have accomplished this

**Comment by martukas** [comment]
#990 took care of this
