### ISSUE TITLE
Upper and Lower Acrylic Face Plates Modeling and Re-design

### ISSUE THREAD

**Issue by KishanKoradiya** [RespiraWorks/Ventilator#938]
**What has to be done**
The upper and lower face plates need to be redesigned and migrated to Inventor. The current models do not facilitate proper assembly.

A successful redesign for the the lower face plate - the filter mounting holes in the lower face plate will allow for accommodation of M4 screws, which the current version does not.
A successful redesign for the upper face plate - [although issues do exist](https://respiraworks.slack.com/archives/C0137BLF17A/p1601532179025600), no changes shall be made now. Migration to Inventor must take place as is.

**How do you know it has to be done**
The current models are in Fusion 360. Mass migration to Inventor is underway.

The following shall be created:

- Inventor Solid Model
- Engineering Drawing (both .idw and exported PDF)
- Dxf file (For laser cutting)

**Comment by martukas** [comment]
This appears to be a subset of #937
