### ISSUE TITLE
Migrate Pinch Valve components to Inventor

### ISSUE THREAD

**Issue by KishanKoradiya** [RespiraWorks/Ventilator#941]
**What has to be done**
The pinch valve components (bearing, base, rotor) need to be migrated to Inventor.

A successful migration to Inventor must take place as is.

**How do you know it has to be done**
The current models are .step files. Mass migration to Inventor is underway.

The following shall be created for all the components of the pinch valve:

Inventor Solid Model
Engineering Drawing (both .idw and exported PDF)
Dxf file (For laser cutting)

**Don't forget**
- [ ] Put the issue in a milestone
- [ ] Assign it to one of the projects
- [ ] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

**Comment by KishanKoradiya** [comment]
Please note:

The [README](https://github.com/RespiraWorks/Ventilator/tree/issue_941_pinchvalve_migration/manufacturing/pinch_valve#custom-parts) has links to external webpage, as quoted below, that required account creation to view. 
   

> Original designs found [here](https://cad.onshape.com/documents/3fe0c1f79c482144c267173d/w/2ad1c08071a25185f9c78c68/e/03a49465e4e026f9f102d0af).

Suggest removing it if we no longer need it.

**Comment by martukas** [comment]
Superseded by #990
