### ISSUE TITLE
PCB mounting solution for Rev A board

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#958]
**What has to be done**
A mounting solution must be devised for PCB Rev A.
The PCB should mount directly to the vertical part of the bent metal frame that supports the main equipment tray. 
* if the exact form factor is know, it should be possible to provision a precise mounting solution.
* if the exact form factor is not yet known, some number of mounting points should be provided allowing some sort of slats or
adapter plate to be used for mounting the PCB.

**How do you know it has to be done**
Experiences in building V0.3 proved that there was no good mounting point for the PCB:
* mounting to metal frame required drilling holes, which was extremely hard to do once the sheet metal was bent into a shape that cannot be conveniently operated on a drill press.
* mounting to the touchscreen is not a sturdy solution long-term, given shock and drop tests will be required

**Code pointers**
TODO

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

**Comment by inceptionev** [comment]
@martukas @tijanim here is a first stab a PCB Rev A floor planning and size envelope (attached)
[20210119-PCB_Physical_Floor_Planning.zip](https://github.com/RespiraWorks/Ventilator/files/5840352/20210119-PCB_Physical_Floor_Planning.zip)

**Comment by martukas** [comment]
![image](https://user-images.githubusercontent.com/1972005/105406768-e19c4a80-5bfa-11eb-875f-a226666234c5.png)

**Comment by martukas** [comment]
@inceptionev has indicated in Slack correspondence that preliminarily this will be 300x150mm with possibly +/-30mm incertainty

**Comment by inceptionev** [comment]
Not +/- 30mm, probably only +.  We don't have a ton of options to make the board smaller, but we are asking if we can extend 30mm in the short dimension (form 150 to 180mm) to give ourselves more margin.  The 3D model is linked 2 comments above.

**Comment by inceptionev** [comment]
The design has proceeded through floor planning and the outline expanded somewhat.  The current dimensions are 350x155mm and the file can be found here: https://github.com/RespiraWorks/Ventilator/blob/pcb_block_layout/pcb/floor-planning/20210312-Ventilator-STEP-DRAFT.zip

*note once the branch merges, this will be in master instead.

**Comment by inceptionev** [comment]
Latest PCB STEP file is here: https://github.com/RespiraWorks/Ventilator/blob/pcb_block_layout/pcb/floor-planning/20210322-Ventilator-STEP-DRAFT.zip

The mounting hole and sensor daughtercard positions have not changed, but some of the connector an components positions have shifted.

![image](https://user-images.githubusercontent.com/8660661/112110053-9dccaf80-8b6f-11eb-8e62-40bfef1e717e.png)

**Comment by martukas** [comment]
RPI header is actually this:
https://www.samtec.com/products/esq-120-44-l-d

**Comment by inceptionev** [comment]
Latest PCB 3D model is here, and now includes connectors: https://github.com/RespiraWorks/Ventilator/blob/pcb_block_layout/pcb/floor-planning/20210326-Ventilator-STEP-DRAFT.zip

The STEP file doesn't render the silkscreen so the connector labels are lost.  Here are a couple screenshots to help with that:

![image](https://user-images.githubusercontent.com/8660661/112705034-3908a200-8e5a-11eb-88ec-4a15774c36b6.png)

![image](https://user-images.githubusercontent.com/8660661/112705078-69e8d700-8e5a-11eb-9005-23a9ee2617da.png)

**Comment by inceptionev** [comment]
Latest PCB 3d Model update.  The PCB is now in final review, so the physical locations of the connectors and mounting locations are not expected to change anymore.

Latest 3D model is here: https://github.com/RespiraWorks/Ventilator/blob/pcb_block_layout/pcb/floor-planning/20210329-Ventilator-STEP-RELEASE-CANDIDATE.zip

Visual guide for connector labels:
![image](https://user-images.githubusercontent.com/8660661/112908738-ea027d00-90a4-11eb-9d60-b6e385702c15.png)

**Comment by inceptionev** [comment]
submitted to manufacturing so this physical layout is now locked.

**Comment by inceptionev** [comment]
Latest 3D model with mounting holes changed to M2.5

https://github.com/RespiraWorks/Ventilator/blob/pcb_block_layout/pcb/floor-planning/20210401-Ventilator-STEP-RELEASE-CANDIDATE.step

**Comment by martukas** [comment]
PCB model has been converted to inventor files and checked in to branch for ticket #957 
There is now a sheet metal part for mounting the PCB that integrated with the main equipment bracket:

![image](https://user-images.githubusercontent.com/1972005/113711803-66075100-96b3-11eb-8ff0-53b42a97edd6.png)
![image](https://user-images.githubusercontent.com/1972005/113711861-70c1e600-96b3-11eb-8932-94f72c76d4e4.png)

The fame is big enough such that if a different form factor PCB will be used, we can have an acrylic panel with custom mounting points.
The frame is also flat enough that drilling additional holes on a drill press should be feasible if that is desired.
