### ISSUE TITLE
Enclosure with two (2) cooling fans

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#962]
**What has to be done**
Enclosure should accommodate 2 equipment cooling fans.
* fans should not interfere with other internal pneumatic components
* fans should be effective at cooling the most heat-prone or heat-sensitive components. Some thought my have to be put into this as stepper motors are below the main equipment tray, while computing equipment is above.

**How do you know it has to be done**
India build indicated excessive heat and need for a second cooling fan.
TODO: link to notes

**Code pointers**
TODO

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

**Comment by inceptionev** [comment]
If we have space constraints, consider using a more powerful fan in the same size envelope, adding holes that allow airflow to cross the pneumatic tray, and providing an outlet for the airflow that opens from the space below the tray.  This will encourage airflow across the stepper motors, which create a lot of heat.  Also pay mind to the steady state temperature of the Raspberry Pi processor, which will throttle back on performance if it overheats.  Here is one that is the same size with 2x the flow and 5x the static pressure: https://www.digikey.com/en/products/detail/nmb-technologies-corporation/08025DA-12P-AA-00/9841655

**Comment by RakurthiLokesh** [comment]
We India team thought of going for two fans initially but later we decided to go for a high powered fan with vent holes to allow the air to flow on the opposite side.

**Comment by martukas** [comment]
Newly designed enclosure side-panels have cut-outs and mounting holes for fans on each side. Two fans can be installed or, alternatively one of those cut-outs can be used to mounting an air filter, or can be blocked off.

The fans are placed at the back so that they maximize air-flow around the most heat sensitive PCB components.

These changes have been checked-in in the branch addressing #957 

![image](https://user-images.githubusercontent.com/1972005/113715505-9224d100-96b7-11eb-8332-a2f45718fdec.png)
![image](https://user-images.githubusercontent.com/1972005/113715549-9d77fc80-96b7-11eb-875b-b80c3b9f3065.png)
