### ISSUE TITLE
Handles on sides of enclosure

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#964]
**What has to be done**
There should be two handles on the sides of the enclosure for carrying the ventilator. They may be of whatever material as long as they do not protrude but are recessed for safety reasons.

**How do you know it has to be done**
The top handle made of bent metal likely has to be eliminated as a safety hazard, as noted in #963

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any

**Comment by martukas** [comment]
Here are some options from McMaster.

Recessed handles:
https://www.mcmaster.com/recessed-pull-handles/handle-style~recessed/mount-type~screw/

Folding:
https://www.mcmaster.com/recessed-pull-handles/mount-type~screw/handle-style~folding/

**Comment by KishanKoradiya** [comment]
The links above have handle models that were unacceptable for various reasons - the recessed models had material that would show on the exterior of the box and was considered ugly and the folding handles were also deemed aesthetically displeasing.

These qualities were laid out as desirable:
- not ugly
- easily installable
- recessed
- protect the hand from sheet metal
- to not get stuff inside

Solution proposed to satisfy these:
A recessed [snap on](https://www.mcmaster.com/handles/mount-type~snap-in/) handle with minimal material on the outside with no screws needed for securement and is easily installable is a great choice imo:
https://www.mcmaster.com/1098A92/   (matches our sheet metal thickness - 1.52mm is approx. 0.06'')
https://www.aliexpress.com/item/4001260324420.html
https://southco.com/en_us_int/handles/flushlow-profile-handles-pulls/p2-flush-pull-lockable-and-nonlockable-versions ([full catalog](https://files.southco.com/static/Literature/p2.en.pdf))

**Comment by martukas** [comment]
Going with this for now:
https://www.mcmaster.com/1098A27/

This is made for panel thickness of 0.03"
If we are using 18 gauge stainless for enclosure panels, those are 0.05", so this is not quite right. Perhaps it can be gently forced to conform?

![image](https://user-images.githubusercontent.com/1972005/113713856-c9927e00-96b5-11eb-8f47-36d0f41fb44f.png)

**Comment by sock8m** [comment]
https://www.mcmaster.com/1098A91/

thickness is for 0.04" to 0.055"

**Comment by sock8m** [comment]
![A91_handle](https://user-images.githubusercontent.com/82127617/114502226-73639480-9bf9-11eb-8a1a-6df08a56f4d5.PNG)

The 1098A91 handle has a different fit then the 1098A27

**Comment by martukas** [comment]
Complete in #1103
