### ISSUE TITLE
Placement of power supply in enclosure

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#965]
**What has to be done**
Must decide where the power supply (adapter) and power jack are to be placed in the enclosure.
* must not interfere with pneumatic assembly
* must include necessary mounting for adapter (which adapter?)
* must have cut-out in the enclosure and secure mounting for power cable (or power jack?)

**How do you know it has to be done**
The v0.3 builds had no provision for any of this, and there was not even a way to run a power cable out of the enclosure without cutting additional holes in metal.

**Code pointers**
TODO

**Don't forget**
- [ ] Put the issue in a milestone
- [ ] Assign it to one of the projects
- [ ] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

**Comment by martukas** [comment]
Blocked by #966 (selection of power supply)

**Comment by martukas** [comment]
We want to keep the ventilator agnostic of the AC power grid, so it will internally be 12V. Thus, no power adapter is integrated into the unit. A selection of the external adapter is tracked in #966 and the enclosure should simply have a plug such as this:
https://www.digikey.com/en/products/detail/kycon-inc/KPJX-PM-4S/9990081

**Comment by tijanim** [comment]
Mirror what was done on front. Acrylic back holding PCB/Battery can also mount switch/power connector. A cutout in the back plate allows access.

**Comment by martukas** [comment]
So, power supply itself is definitely external.
Having a connector on the enclosure is addressed in #1040
